Se restaura valores anteriores

diff --git a/.github/workflows/devsecops-pipeline.yml b/.github/workflows/devsecops-pipeline.yml
--- a/.github/workflows/devsecops-pipeline.yml
+++ b/.github/workflows/devsecops-pipeline.yml
@@ -35,7 +35,6 @@ jobs:
           DEFECTDOJO_PRODUCT_NAME: "DevSecOps Engagement"
           DEFECTDOJO_ENVIRONMENT: "CI/CD-Pipeline"
         run: |
-          rm -f semgrep_report.json
           if [ -s semgrep_report.json ] && [ "$(jq '.results | length' semgrep_report.json)" -gt 0 ]; then
             response=$(curl -s -o response_body.txt -w "%{http_code}" -X POST "$DEFECTDOJO_URL/api/v2/import-scan/" \
               -H "Authorization: Token $DEFECTDOJO_API_KEY" \
@@ -79,6 +78,32 @@ jobs:
             jq -r '.Results[]?.Vulnerabilities[]? | "| " + (.VulnerabilityID // "N/A") + " | " + (.PkgName // "N/A") + " | " + (.Severity // "N/A") + " |"' trivy_report.json
           else
             echo "No vulnerabilities found in Trivy."
+          fi
+
+      - name: Upload Trivy Report to DefectDojo
+        env:
+          DEFECTDOJO_URL: ${{ secrets.DEFECTDOJO_URL }}
+          DEFECTDOJO_API_KEY: ${{ secrets.DEFECTDOJO_API_KEY }}
+          DEFECTDOJO_ENGAGEMENT_ID: ${{ secrets.DEFECTDOJO_ENGAGEMENT_ID }}
+          DEFECTDOJO_PRODUCT_NAME: "DevSecOps Engagement"
+          DEFECTDOJO_ENVIRONMENT: "CI/CD-Pipeline"
+        run: |
+          if [ -s trivy_report.json ] && [ "$(jq '.Results | length' trivy_report.json)" -gt 0 ]; then
+            response=$(curl -s -o response_body.txt -w "%{http_code}" -X POST "$DEFECTDOJO_URL/api/v2/import-scan/" \
+              -H "Authorization: Token $DEFECTDOJO_API_KEY" \
+              -H "Content-Type: multipart/form-data" \
+              -F "scan_type=Trivy Scan" \
+              -F "engagement=$DEFECTDOJO_ENGAGEMENT_ID" \
+              -F "product_name=$DEFECTDOJO_PRODUCT_NAME" \
+              -F "environment=$DEFECTDOJO_ENVIRONMENT" \
+              -F "file=@trivy_report.json")
+            http_code=$(tail -n1 <<< "$response")
+            if [ "$http_code" -ne 201 ]; then
+              echo "Error uploading Trivy report. HTTP Code: $http_code"
+              exit 1
+            fi
+          else
+            echo "No vulnerabilities found or report file missing. Skipping upload."
           fi
 
   gitleaks:
