Se plantean cambios de versiones

diff --git a/.github/workflows/devsecops-pipeline.yml b/.github/workflows/devsecops-pipeline.yml
--- a/.github/workflows/devsecops-pipeline.yml
+++ b/.github/workflows/devsecops-pipeline.yml
@@ -3,45 +3,6 @@ name: DevSecOps Pipeline
 on: [push, pull_request]
 
 jobs:
-  gitleaks:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
-
-      - name: Run Gitleaks
-        uses: zricethezav/gitleaks-action@v1.6.0
-        with:
-          config-path: .github/.gitleaks.toml
-
-      - name: Display Gitleaks Results
-        run: |
-          if [ -s gitleaks_report.json ]; then
-            echo "### Gitleaks Vulnerabilities Found:"
-            jq -r '.results[]? | "| " + (.file // "N/A") + " | " + (.rule // "N/A") + " | " + (.commit // "N/A") + " |"' gitleaks_report.json || echo "No vulnerabilities found."
-          else
-            echo "No vulnerabilities found."
-          fi
-
-      - name: Upload Gitleaks Report to DefectDojo
-        env:
-          DEFECTDOJO_URL: ${{ secrets.DEFECTDOJO_URL }}
-          DEFECTDOJO_API_KEY: ${{ secrets.DEFECTDOJO_API_KEY }}
-          DEFECTDOJO_ENGAGEMENT_ID: ${{ secrets.DEFECTDOJO_ENGAGEMENT_ID }}
-          DEFECTDOJO_PRODUCT_NAME: "DevSecOps Engagement"
-        run: |
-          if [ -s gitleaks_report.json ] && [ "$(jq '.results | length' gitleaks_report.json)" -gt 0 ]; then
-            curl -X POST "$DEFECTDOJO_URL/api/v2/import-scan/" \
-              -H "Authorization: Token $DEFECTDOJO_API_KEY" \
-              -H "Content-Type: multipart/form-data" \
-              -F "scan_type=Gitleaks Scan" \
-              -F "engagement=$DEFECTDOJO_ENGAGEMENT_ID" \
-              -F "product_name=$DEFECTDOJO_PRODUCT_NAME" \
-              -F "file=@gitleaks_report.json"
-          else
-            echo "No vulnerabilities found or report file missing. Skipping upload."
-          fi
-
   semgrep:
     runs-on: ubuntu-latest
     steps:
@@ -74,13 +35,19 @@ jobs:
           DEFECTDOJO_PRODUCT_NAME: "DevSecOps Engagement"
         run: |
           if [ -s semgrep_report.json ] && [ "$(jq '.results | length' semgrep_report.json)" -gt 0 ]; then
-            curl -X POST "$DEFECTDOJO_URL/api/v2/import-scan/" \
+            response=$(curl -s -w "%{http_code}" -X POST "$DEFECTDOJO_URL/api/v2/import-scan/" \
               -H "Authorization: Token $DEFECTDOJO_API_KEY" \
               -H "Content-Type: multipart/form-data" \
               -F "scan_type=Semgrep JSON Report" \
               -F "engagement=$DEFECTDOJO_ENGAGEMENT_ID" \
               -F "product_name=$DEFECTDOJO_PRODUCT_NAME" \
-              -F "file=@semgrep_report.json"
+              -F "file=@semgrep_report.json")
+
+            http_code="${response: -3}"
+            if [ "$http_code" -ne 201 ]; then
+              echo "Error uploading Semgrep report. Server response: $response"
+              exit 1
+            fi
           else
             echo "No vulnerabilities found or report file missing. Skipping upload."
           fi
@@ -94,8 +61,9 @@ jobs:
       - name: Install Trivy
         run: |
           sudo apt-get install -y wget
-          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.46.0_Linux-64bit.tar.gz
-          tar zxvf trivy_0.46.0_Linux-64bit.tar.gz
+          TRIVY_LATEST_VERSION=$(curl -s https://api.github.com/repos/aquasecurity/trivy/releases/latest | jq -r '.tag_name' | sed 's/v//')
+          wget "https://github.com/aquasecurity/trivy/releases/download/v${TRIVY_LATEST_VERSION}/trivy_${TRIVY_LATEST_VERSION}_Linux-64bit.tar.gz"
+          tar zxvf "trivy_${TRIVY_LATEST_VERSION}_Linux-64bit.tar.gz"
           sudo mv trivy /usr/local/bin/
           trivy --version
 
@@ -119,13 +87,19 @@ jobs:
           DEFECTDOJO_PRODUCT_NAME: "DevSecOps Engagement"
         run: |
           if [ -s trivy_report.json ] && [ "$(jq '.Results | length' trivy_report.json)" -gt 0 ]; then
-            curl -X POST "$DEFECTDOJO_URL/api/v2/import-scan/" \
+            response=$(curl -s -w "%{http_code}" -X POST "$DEFECTDOJO_URL/api/v2/import-scan/" \
               -H "Authorization: Token $DEFECTDOJO_API_KEY" \
               -H "Content-Type: multipart/form-data" \
               -F "scan_type=Trivy Scan" \
               -F "engagement=$DEFECTDOJO_ENGAGEMENT_ID" \
               -F "product_name=$DEFECTDOJO_PRODUCT_NAME" \
-              -F "file=@trivy_report.json"
+              -F "file=@trivy_report.json")
+
+            http_code="${response: -3}"
+            if [ "$http_code" -ne 201 ]; then
+              echo "Error uploading Trivy report. Server response: $response"
+              exit 1
+            fi
           else
             echo "No vulnerabilities found or report file missing. Skipping upload."
           fi
